pod 'UITableView+FDTemplateLayoutCell', '~> 1.3'

pod 'AFNetworking', '~> 2.5.4'

pod 'MJRefresh', '~> 1.4.7'

pod 'MJExtension', '~> 2.3.7'

pod 'MagicalRecord', '~> 2.3.0'

pod 'MGSwipeTableCell', '~> 1.5.1'

pod 'DZNEmptyDataSet', '~> 1.7'
